blank_issues_enabled: false
contact_links:
  - name: ❌ Help with Extensions
    url: https://kainotch.github.io/WammyWeb/
    about: For extension-related questions/issues
  - name: 🖥️ Wammy website
    url: https://kainotch.github.io/WammyWeb/
    about: Guides, troubleshooting, and answers to common questions
